Fix DB error updating category on PostgreSQL
ERROR: invalid input syntax for type integer: "TRUE" for the query:
UPDATE mantis_category_table SET name=$1, user_id=$2, status=$3
WHERE id=$4.

Regression introduced by commit b97858eee5c83e64e44f40a0010163a44e44aae9
(issue #31017).

Fixes #36263